name: install-repo
description: 'Install repository'
runs:
  using: composite
  steps:
    - name: Install Repository
      shell: bash -el {0}
      run: |
        python -m pip install -v -e .

        # Test import.
        python -c 'import sys; sys.path = sys.path[1:]; import xformers'
        ls xformers
        python -m xformers.info