name: Tests

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'xformers/**'
    #   - '.github/workflows/test.yml'
    #   - 'setup.py'
    #   - 'requirements.*'
    #   - '.circleci/**'
jobs:
  cpu_tests_py38:
    runs-on: 4-core-ubuntu-latest
    env:
      MAX_JOBS: "4"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Remove internal components, as they require GPU
        run: |
          mkdir -p .github/sync.fairinternal
          touch .github/sync.fairinternal/ossify.sh
          chmod +x .github/sync.fairinternal/ossify.sh
          .github/sync.fairinternal/ossify.sh
      - name: Setup Miniconda
        id: setup-miniconda
        uses: ./.github/actions/setup-miniconda
      - name: Install Dependencies
        if: steps.setup-miniconda.outputs.cache-hit != 'true'
        uses: ./.github/actions/install-dep
      - name: Check PyTorch version
        uses: ./.github/actions/check-torch
        with:
          major: 2
          minor: 1
      - name: Run unit tests
        uses: ./.github/actions/run-unittests
      - name: Run doc build
        uses: ./.github/actions/run-doc-build
      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results